import requests


def generate_business_report(insights: str, model: str = "llama3.2:1b") -> str:
    """
    Generate a professional business report from structured insights
    using a local Ollama model.

    The default model is a lightweight local model to reduce memory usage
    and improve compatibility on machines with limited RAM.

    Parameters
    ----------
    insights : str
        Structured business insights generated by the analytics pipeline.
    model : str, optional
        Name of the local Ollama model to use.

    Returns
    -------
    str
        AI-generated executive business report.
    """

    prompt = f"""
You are a senior business analyst.

Write a concise and professional executive business report based on the following business insights.

The report should be clear, structured, and written for business stakeholders.

Use this structure:
- Executive Summary
- Key Performance Insights
- Risks or Declines
- Growth Drivers
- Recommended Next Actions

Business Insights:
{insights}
"""

    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
        timeout=120,
    )

    response.raise_for_status()

    result = response.json()

    return result["response"]